// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {postgres} from '../models';

export function DescribeTable(arg1:string,arg2:string,arg3:string):Promise<postgres.TableDetails>;

export function ListSchemas(arg1:string):Promise<Array<postgres.SchemaSummary>>;

export function ListTables(arg1:string,arg2:string):Promise<Array<postgres.TableSummary>>;

export function RefreshMetadata(arg1:string):Promise<Array<postgres.SchemaSummary>>;
