// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['updater']['Service']['CheckForUpdate']();
}

export function GetReleaseState() {
  return window['go']['updater']['Service']['GetReleaseState']();
}

export function InstallUpdate(arg1) {
  return window['go']['updater']['Service']['InstallUpdate'](arg1);
}
