// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';

export function CheckForUpdate():Promise<updater.UpdateCheckResult>;

export function GetReleaseState():Promise<updater.ReleaseState>;

export function InstallUpdate(arg1:updater.InstallUpdateRequest):Promise<updater.InstallUpdateResult>;
