// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['connections']['Service']['Connect'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['connections']['Service']['DeleteConnection'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['connections']['Service']['Disconnect'](arg1);
}

export function ListConnections() {
  return window['go']['connections']['Service']['ListConnections']();
}

export function SaveConnection(arg1) {
  return window['go']['connections']['Service']['SaveConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['connections']['Service']['TestConnection'](arg1);
}
