// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connections} from '../models';

export function Connect(arg1:connections.ConnectRequest):Promise<connections.ConnectionStatus>;

export function DeleteConnection(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function ListConnections():Promise<Array<connections.ConnectionProfile>>;

export function SaveConnection(arg1:connections.SaveConnectionRequest):Promise<connections.ConnectionProfile>;

export function TestConnection(arg1:connections.TestConnectionRequest):Promise<connections.ConnectionStatus>;
