// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCredential(arg1) {
  return window['go']['ai']['Service']['DeleteCredential'](arg1);
}

export function GenerateSQL(arg1) {
  return window['go']['ai']['Service']['GenerateSQL'](arg1);
}

export function GetCredentialStatus(arg1) {
  return window['go']['ai']['Service']['GetCredentialStatus'](arg1);
}

export function ListCredentials() {
  return window['go']['ai']['Service']['ListCredentials']();
}

export function SaveCredential(arg1) {
  return window['go']['ai']['Service']['SaveCredential'](arg1);
}
