// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ai} from '../models';

export function DeleteCredential(arg1:string):Promise<void>;

export function GenerateSQL(arg1:ai.GenerateRequest):Promise<ai.GenerateResponse>;

export function GetCredentialStatus(arg1:string):Promise<ai.CredentialStatus>;

export function ListCredentials():Promise<Array<ai.CredentialStatus>>;

export function SaveCredential(arg1:ai.SaveCredentialRequest):Promise<ai.CredentialStatus>;
