// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {query} from '../models';

export function AnalyzeSQL(arg1:string):Promise<query.SQLAnalysis>;

export function CancelQuery(arg1:string):Promise<void>;

export function ExecuteQuery(arg1:query.QueryRequest):Promise<query.QueryResult>;

export function ExplainQuery(arg1:query.QueryRequest):Promise<query.QueryResult>;

export function GetQueryHistory():Promise<Array<query.QueryHistoryItem>>;
