// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeSQL(arg1) {
  return window['go']['query']['Service']['AnalyzeSQL'](arg1);
}

export function CancelQuery(arg1) {
  return window['go']['query']['Service']['CancelQuery'](arg1);
}

export function ExecuteQuery(arg1) {
  return window['go']['query']['Service']['ExecuteQuery'](arg1);
}

export function ExplainQuery(arg1) {
  return window['go']['query']['Service']['ExplainQuery'](arg1);
}

export function GetQueryHistory() {
  return window['go']['query']['Service']['GetQueryHistory']();
}
