// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fileexport} from '../models';

export function SaveExport(arg1:fileexport.SaveExportRequest):Promise<fileexport.SaveExportResult>;
