// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveExport(arg1) {
  return window['go']['fileexport']['Service']['SaveExport'](arg1);
}
