// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appdata} from '../models';

export function ClearAIChatMessages(arg1:appdata.ClearAIChatMessagesRequest):Promise<void>;

export function CloseAll():Promise<void>;

export function CreateAIChatThread(arg1:appdata.CreateAIChatThreadRequest):Promise<appdata.AIChatThread>;

export function DeleteAIChatThread(arg1:appdata.DeleteAIChatThreadRequest):Promise<void>;

export function ListAIChatMessages(arg1:appdata.ListAIChatMessagesRequest):Promise<Array<appdata.AIChatMessage>>;

export function ListAIChatThreads(arg1:appdata.ListAIChatThreadsRequest):Promise<Array<appdata.AIChatThread>>;

export function ListQueryHistory(arg1:appdata.ListQueryHistoryRequest):Promise<Array<appdata.QueryHistoryEntry>>;

export function SaveAIChatMessage(arg1:appdata.SaveAIChatMessageRequest):Promise<appdata.AIChatMessage>;

export function SaveQueryHistory(arg1:appdata.SaveQueryHistoryRequest):Promise<appdata.QueryHistoryEntry>;

export function UpdateAIChatThread(arg1:appdata.UpdateAIChatThreadRequest):Promise<appdata.AIChatThread>;
