// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAIChatMessages(arg1) {
  return window['go']['appdata']['Service']['ClearAIChatMessages'](arg1);
}

export function CloseAll() {
  return window['go']['appdata']['Service']['CloseAll']();
}

export function CreateAIChatThread(arg1) {
  return window['go']['appdata']['Service']['CreateAIChatThread'](arg1);
}

export function DeleteAIChatThread(arg1) {
  return window['go']['appdata']['Service']['DeleteAIChatThread'](arg1);
}

export function ListAIChatMessages(arg1) {
  return window['go']['appdata']['Service']['ListAIChatMessages'](arg1);
}

export function ListAIChatThreads(arg1) {
  return window['go']['appdata']['Service']['ListAIChatThreads'](arg1);
}

export function ListQueryHistory(arg1) {
  return window['go']['appdata']['Service']['ListQueryHistory'](arg1);
}

export function SaveAIChatMessage(arg1) {
  return window['go']['appdata']['Service']['SaveAIChatMessage'](arg1);
}

export function SaveQueryHistory(arg1) {
  return window['go']['appdata']['Service']['SaveQueryHistory'](arg1);
}

export function UpdateAIChatThread(arg1) {
  return window['go']['appdata']['Service']['UpdateAIChatThread'](arg1);
}
