// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';

export function GetSettings():Promise<settings.AppSettings>;

export function UpdateSettings(arg1:settings.AppSettings):Promise<settings.AppSettings>;
