// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {context} from '../models';
import {time} from '../models';

export function GetSettings():Promise<settings.AppSettings>;

export function OpenSettingsFile():Promise<void>;

export function SanitizeSettingsFile():Promise<void>;

export function UpdateSettings(arg1:settings.AppSettings):Promise<settings.AppSettings>;

export function WatchSettingsFile(arg1:context.Context,arg2:time.Duration,arg3:any):Promise<void>;
